baseURL = "https://www.valentinsavenko.com/"
languageCode = "en-us"
# theme = "raditian-free-hugo-theme"
theme = "vs-free-hugo-theme"


# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"

# navigation
[menu]

[[menu.header]]
URL = "#about"
name = "About"
weight = 2

# [[menu.header]]
# URL = "#portfolio"
# name = "Portfolio"
# weight = 3

# [[menu.header]]
# URL = "#contact"
# name = "Contact"
# weight = 4

[[menu.footer]]
URL = "#about"
name = "About"
weight = 2

# [[menu.footer]]
# URL = "#portfolio"
# name = "Portfolio"
# weight = 3

# [[menu.footer]]
# URL = "#contact"
# name = "Contact"
# weight = 4

[params]

sections = [
    "showcase", 
    "about",  
    "experience",
    "education"
]
# sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact"]

googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

[params.logo]
text1 = "Valentin"
text2 = "Savenko"

[params.footer]
copyright = "Â© Valentin Savenko. All rights reserved."
